In [7]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix,accuracy_score

In [8]:
iris = load_iris()
print(iris.feature_names)
print(iris.data)
print(iris.target_names)
print(iris.target)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3

In [9]:
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.25)

In [10]:
n=10
loss_cur = 999
classifier = MLPClassifier(hidden_layer_sizes=(4,3),activation='logistic',solver='sgd',learning_rate_init=5,verbose=True,warm_start=True)
for _ in range(n):
    classifier.fit(x_train,y_train)
    loss_prev = loss_cur
    loss_cur = classifier.loss_
    for i in classifier.coefs_:
        print(i,end='\n\n')
ypred = classifier.predict(x_test)


Iteration 1, loss = 1.12348433
Iteration 2, loss = 1.50544688
Iteration 3, loss = 2.65854318
Iteration 4, loss = 2.60547357
Iteration 5, loss = 2.40095299
Iteration 6, loss = 2.81465331
Iteration 7, loss = 1.67204968
Iteration 8, loss = 1.11564652
Iteration 9, loss = 1.18684784
Iteration 10, loss = 1.22695153
Iteration 11, loss = 1.36609201
Iteration 12, loss = 1.36736021
Iteration 13, loss = 1.28053344
Iteration 14, loss = 1.45233760
Iteration 15, loss = 1.28330869
Iteration 16, loss = 1.37395649
Iteration 17, loss = 1.33461751
Iteration 18, loss = 1.46030189
Iteration 19, loss = 1.25732685
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
[[-1.75271472e+00  2.60064573e+00 -1.19208131e+00  2.93543532e+00]
 [-1.01915735e+00  1.05501187e+00 -6.84600951e-01  2.41690803e+00]
 [-1.10558501e+00  1.27107474e+00 -8.77927231e-01  1.42143758e+00]
 [-4.12007429e-01 -1.88184820e-03 -4.64785770e-01  5.51195525e-01]]

[[ -0.06108034   0.13199049  -0.20305119]

In [11]:
cm = confusion_matrix(y_test,ypred)
print("Confusion matrix : \n",cm)
acc = accuracy_score(y_test,ypred)
print("Accuracy score : \n",acc)


Confusion matrix : 
 [[ 0 13  0]
 [ 0 10  0]
 [ 0 15  0]]
Accuracy score : 
 0.2631578947368421


In [12]:
print("Weight Matrices\n")
for i in classifier.coefs_:
    print(i,end='\n\n')


Weight Matrices

[[-1.75258092e+00  2.60044721e+00 -1.19199031e+00  2.93521124e+00]
 [-1.01907955e+00  1.05493134e+00 -6.84548691e-01  2.41672354e+00]
 [-1.10550062e+00  1.27097771e+00 -8.77860213e-01  1.42132907e+00]
 [-4.11975978e-01 -1.88170455e-03 -4.64750290e-01  5.51153448e-01]]

[[ -0.06107568   0.13198041  -0.20303569]
 [ -7.52973334  -4.60411394  -3.52375613]
 [ -0.31063314  -0.41521483   0.05889956]
 [-10.9322035   -6.73045874  -5.79286876]]

[[-3.16915123  0.08907462  3.74312069]
 [-4.25493269  1.13232172  2.53414214]
 [-2.79068182  1.48844691  2.12513529]]

